[package]
name = "cve-exporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
serde_json = "1.0.41"
chrono = {version = "0.4.24", features = ["serde"]}
serde = {version = "1.0"}
bson = {version = "2.6.1", features = ["chrono-0_4"]}
futures = "0.3.27"
atomic-counter = "1.0.1"
clap = {version= "4.1.11", features = ["derive"]}

[dependencies.mongodb]
version = "2.4.0"
default-features = false
features = ["async-std-runtime"]

[profile.release]
strip = true  # Automatically strip symbols from the binary.
# opt-level = "z"  # Optimize for size.
lto = true
codegen-units = 1